// src/lib/lore/reseedWorld.ts
// Lore-aware world generation: regenerate a campaign's world structure
// from its imported canon. Shared by the admin "Reseed world from lore"
// button (api/campaigns/[id]/reseed-from-lore) and the automatic
// creation-time path (loreQueue fires this when a job created alongside
// the campaign finishes importing).
//
// Two merge modes, decided by whether anyone has committed to the world:
//
// FRESH (no characters yet — e.g. right after creation, before the
// background import finished): the provisional generated world is
// REPLACED by the canon one. Non-canon factions are retired (deactivated
// + hidden, never deleted — FK-safe), the unreferenced capability
// scaffold is rebuilt, stat labels / corruption theme / archetypes are
// regenerated from canon.
//
// LIVE (characters exist): strictly non-destructive. Factions and
// capabilities are additive, stat labels and the corruption theme fill in
// only if absent, archetypes are left alone — UNLESS the campaign
// currently has zero (a previous generation attempt failed/timed out
// partway through and never recovered), in which case archetypes are
// still (re)generated so the "Reseed from lore" admin button is a real
// recovery path even after characters exist, not just a fresh-mode-only
// escape hatch.
//
// NPCs and locations are purely additive in BOTH modes, like fronts — they
// have no stable canon identity to dedupe cleanly against a "provisional
// vs canon" distinction, so fresh mode doesn't retire existing ones here.
// Generated by the extras (generateWorldExtras) call alongside archetypes,
// NOT the primary generateWorldFromTemplate call — that call already runs
// close to its own token budget, and adding more required fields risks
// truncating its JSON response, which fails the whole thing (zero
// factions/capabilities/fronts, not just zero NPCs/locations). The extras
// call runs on every reseed now (previously skipped when archetypes/theme
// were already satisfied) so NPCs/locations are always attempted.

import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { hasCorruptionTheme } from '@/lib/game/corruption'
import { isConfidentFuzzyMatch } from '@/lib/game/entityResolution'
import { generateWorldFromTemplate } from '@/lib/ai/worldGenerator'
import { generateWorldExtras } from '@/lib/ai/worldExtras'
import { generateMoveFlavor } from '@/lib/ai/moveFlavor'
import { generateWorldRules, generatedRulesToWorldRules } from '@/lib/ai/worldRulesGenerator'
import { generateWorldGraph } from '@/lib/ai/worldGraphGenerator'
import { buildLoreDigest } from './loreDigest'
import { retrieveRelevantLore } from '@/lib/ai/loreRetrieval'
import { createFactionsForCampaign, createNPCsForCampaign, createLocationsForCampaign } from '@/lib/templates/campaign-templates'
import { slugifyCapabilityKey } from '@/lib/game/capabilities'
import { BASIC_MOVES } from '@/lib/pbta-moves'

// The extras call already carries factions + capability keys, so it needs
// less raw canon than base world generation does. Raised 3x alongside
// loreDigest.ts's DIGEST_MAX_CHARS, preserving the same ~50%-of-full-digest
// ratio rather than leaving this squeeze at its old absolute size.
const EXTRAS_DIGEST_CHARS = 18000

export interface ReseedSummary {
  fresh: boolean
  loreEntriesSampled: number
  loreEntriesTotal: number
  factionsAdded: string[]
  factionsRetired: string[]
  factionsAlreadyPresent: number
  capabilitiesAdded: string[]
  frontsAdded: string[]
  npcsAdded: string[]
  locationsAdded: string[]
  statLabelsSet: boolean
  corruptionThemeSet: boolean
  archetypesReplaced: number
  archetypesSkipped: boolean
  movesFlavored: number
  worldRulesSet: boolean
  worldGraphEdgesSet: number
}

export type ReseedResult =
  | { ok: true; summary: ReseedSummary }
  | { ok: false; reason: 'not_found' | 'no_lore' | 'generation_failed' }

/**
 * Pure: which generated factions to add, and (fresh mode only) which
 * existing ones to retire because canon replaced them. Name comparison is
 * case-insensitive; a generated faction matching an existing name keeps
 * the existing row.
 */
export function planFactionMerge(
  existingNames: string[],
  generatedNames: string[],
  fresh: boolean
): { toAdd: string[]; toRetire: string[] } {
  return {
    toAdd: generatedNames.filter(n => !matchesAnyName(n, existingNames)),
    toRetire: fresh
      ? existingNames.filter(n => !matchesAnyName(n, generatedNames))
      : [],
  }
}

/**
 * Pure: which generated fronts are actually new, by name (case-insensitive)
 * against every currently-unresolved clock in the campaign. Purely
 * additive in both fresh and live mode — see the doc comment at the call
 * site for why fronts don't get a fresh-mode "retire" step like factions do.
 */
export function planFrontMerge(existingClockNames: string[], generatedFrontNames: string[]): string[] {
  return generatedFrontNames.filter(n => !matchesAnyName(n, existingClockNames))
}

/**
 * Does `name` correspond to something already in `pool`?
 *
 * Exact (case/whitespace-insensitive) first, then the same tightly-gated
 * fuzzy matcher AI-reported entity names already go through
 * (isConfidentFuzzyMatch — edit distance <=2 AND <=20% of length, built to
 * catch typos and punctuation drift, never a genuinely different name).
 *
 * Matching was previously exact-only, which is a real problem specifically
 * for lore import: canon routinely names an entity slightly differently
 * from whatever the world generator invented for it ("The Ashcrown Court"
 * vs "Ashcrown Court"). Exact-only treated those as unrelated, so in FRESH
 * mode a reseed could retire the existing faction AND create a near-
 * duplicate under the canon spelling in the same pass — orphaning
 * everything already linked to the old row.
 */
export function matchesAnyName(name: string, pool: string[]): boolean {
  const stripped = stripLeadingArticle(name)
  return pool.some(
    candidate =>
      isConfidentFuzzyMatch(name, candidate) ||
      isConfidentFuzzyMatch(stripped, stripLeadingArticle(candidate))
  )
}

/**
 * Drop a leading English article before comparing.
 *
 * isConfidentFuzzyMatch alone is not enough here, and it's worth being
 * precise about why: it allows an edit distance of 2, which covers typos
 * and punctuation ("Kesler"/"Kessler", "Thieves' Guild"/"Thieves Guild")
 * but NOT "The Ashcrown Court" vs "Ashcrown Court" — that's a 4-character
 * difference and fails the gate. Article drift is the single most common
 * shape of this collision in lore import, since canon and the world
 * generator disagree about definite articles constantly.
 *
 * Stripping the article is deliberately narrower than loosening the edit
 * distance would be: it can't collapse two genuinely different short names
 * the way a bigger distance budget could.
 */
export function stripLeadingArticle(name: string): string {
  return name.trim().replace(/^(the|a|an)\s+/i, '')
}

/**
 * Release the creation-time play lock (Campaign.pendingWorldSeed). Lives
 * here rather than in seedingGate.ts so loreQueue can import it without a
 * module cycle (seedingGate → loreQueue → this file).
 */
export async function clearPendingWorldSeed(campaignId: string): Promise<void> {
  await prisma.campaign.updateMany({
    where: { id: campaignId, pendingWorldSeed: true },
    data: { pendingWorldSeed: false },
  })
}

export interface ReseedOptions {
  // Admin opt-in: overwrite stat labels from canon even in live mode,
  // where everything else stays fill-only/additive. See the schema
  // comment on ReseedJob.forceStatLabels for why this one field is safe
  // to treat differently.
  forceStatLabels?: boolean
}

export async function reseedWorldFromLore(campaignId: string, options: ReseedOptions = {}): Promise<ReseedResult> {
  const campaign = await prisma.campaign.findUnique({ where: { id: campaignId } })
  if (!campaign) return { ok: false, reason: 'not_found' }

  const lore = await buildLoreDigest(prisma, campaignId)
  if (!lore) return { ok: false, reason: 'no_lore' }

  // buildLoreDigest samples evenly across the whole corpus BY CHUNK INDEX,
  // which systematically under-represents a short, single-chunk reference
  // page (e.g. a page that just lists a series' named stat system) against
  // long multi-chunk ones (a 30KB chapter-summary page can eat dozens of
  // sample slots). A campaign's stat system is exactly the kind of short,
  // high-signal page that gets diluted out by chance alone. Targeted
  // semantic retrieval guarantees it survives regardless of the broad
  // digest's luck. minSimilarity is lower than loreRetrieval's per-scene
  // default (0.75) since this is a synthetic query, not a real question,
  // and this runs once per reseed rather than once per scene.
  const statLore = await retrieveRelevantLore(
    campaignId,
    'character attributes stats abilities power system status',
    { maxEntries: 2, minSimilarity: 0.5 }
  )
  const statLoreBlock = statLore.length > 0
    ? `\n\n### Character attribute/stat system (if this is a real, named system in canon)\n${statLore.map(e => `${e.title}: ${e.content}`).join('\n\n')}`
    : ''

  const characterCount = await prisma.character.count({ where: { campaignId } })
  const fresh = characterCount === 0

  const generated = await generateWorldFromTemplate(
    null,
    campaign.title,
    campaign.description || '',
    campaign.universe || undefined,
    // The existing opening situation stays canon — reseeding restructures
    // the world's pillars, it doesn't retcon how the story opened.
    campaign.initialWorldSeed || undefined,
    lore.digest + statLoreBlock
  )
  if (!generated) return { ok: false, reason: 'generation_failed' }

  // --- Factions ------------------------------------------------------------
  const existingFactions = await prisma.faction.findMany({
    where: { campaignId },
    select: { name: true, description: true, isActive: true },
  })
  const plan = planFactionMerge(
    existingFactions.filter(f => f.isActive).map(f => f.name),
    generated.factions.map(f => f.name),
    fresh
  )
  const newFactions = generated.factions.filter(f => plan.toAdd.includes(f.name))
  if (newFactions.length > 0) {
    await createFactionsForCampaign(campaignId, prisma, newFactions)
  }
  if (plan.toRetire.length > 0) {
    // Retire, never delete: tick logs / wars / standings may reference the
    // rows, and an inactive+undiscovered faction is invisible to both the
    // simulation and the players.
    await prisma.faction.updateMany({
      where: { campaignId, name: { in: plan.toRetire } },
      data: { isActive: false, isDiscovered: false },
    })
  }

  // --- Capability scaffold ---------------------------------------------------
  if (fresh) {
    // Rebuild: drop scaffold nodes nobody's sheet references (with zero
    // characters that is all of them; the guard keeps this safe if a
    // character appears mid-flight).
    await prisma.campaignCapability.deleteMany({
      where: { campaignId, characterStates: { none: {} } },
    })
  }
  const existingCaps = await prisma.campaignCapability.findMany({
    where: { campaignId },
    select: { key: true, name: true, description: true, domain: true, tier: true, isSecret: true },
  })
  const existingCapKeys = new Set(existingCaps.map(c => c.key))
  const newCaps = generated.capabilities.filter(
    c => !existingCapKeys.has(slugifyCapabilityKey(c.name))
  )
  if (newCaps.length > 0) {
    await prisma.campaignCapability.createMany({
      data: newCaps.map(c => ({
        campaignId,
        key: slugifyCapabilityKey(c.name),
        name: c.name,
        description: c.description || null,
        domain: c.domain,
        tier: c.tier,
        isSecret: c.isSecret,
      })),
      skipDuplicates: true,
    })
  }

  // --- Fronts: purely additive in both modes ---------------------------------
  // Unlike factions/capabilities, fronts have no stable canon identity to
  // dedupe cleanly against a "provisional vs canon" distinction, so fresh
  // mode does NOT retire existing ones here — only new, name-deduped fronts
  // are added. Worst case on a repeatedly-reseeded campaign is a handful of
  // extra danger clocks, never a wrongly-deleted GM-authored one.
  const existingClocks = await prisma.clock.findMany({
    where: { campaignId, resolvedAt: null },
    select: { name: true },
  })
  const newFrontNames = new Set(
    planFrontMerge(existingClocks.map(c => c.name), generated.fronts.map(f => f.name))
  )
  const newFronts = generated.fronts.filter(f => newFrontNames.has(f.name))
  if (newFronts.length > 0) {
    for (const front of newFronts) {
      let relatedFactionId: string | undefined
      if (front.sourceFactionName) {
        const faction = await prisma.faction.findFirst({
          where: { campaignId, name: { equals: front.sourceFactionName, mode: 'insensitive' } },
          select: { id: true },
        })
        relatedFactionId = faction?.id
      }
      await prisma.clock.create({
        data: {
          campaignId,
          name: front.name,
          description: front.description,
          category: front.category,
          maxTicks: front.maxTicks,
          consequence: front.consequence,
          relatedFactionId, // NOT sourceFactionId — see the schema comment
        },
      })
    }
  }

  // --- NPCs + Locations: purely additive in both modes ------------------------
  // Same reasoning as fronts above — no clean provisional-vs-canon identity
  // to retire by, so this only ever adds name-deduped new ones. Previously
  // world generation never produced NPCs/Locations at all (only factions,
  // capabilities, and fronts), so even a campaign built entirely from a
  // lore import had nothing but faction/front stubs in its wiki until
  // actual play introduced anyone — this closes that gap on every reseed,
  // not just at creation.
  // --- Stat labels -----------------------------------------------------------
  // Fresh: canon replaces the provisional labels. Live: fill-only, unless
  // the admin explicitly asked to overwrite (options.forceStatLabels) —
  // see ReseedOptions above for why this one field gets an escape hatch
  // the rest of live mode doesn't.
  let statLabelsSet = false
  if (generated.statLabels && (fresh || !campaign.statLabels || options.forceStatLabels)) {
    await prisma.campaign.update({
      where: { id: campaignId },
      data: { statLabels: generated.statLabels as object },
    })
    statLabelsSet = true
  }

  // --- Move flavor -----------------------------------------------------------
  // Same recovery reasoning as archetypes below: a live campaign missing
  // flavor for one or more of the fixed BASIC_MOVES means a previous
  // generation attempt failed/was interrupted, so "Reseed from lore" is a
  // real fix for that too, not just a fresh-mode escape hatch. Fresh mode
  // replaces provisional flavor with canon-grounded flavor (same as
  // archetypes' atomic delete+recreate); live mode only fills in whichever
  // canonical keys are still missing, never overwriting existing flavor a
  // GM or earlier generation already gave this campaign.
  const existingMoveFlavor = await prisma.move.findMany({
    where: { campaignId, baseMoveKey: { not: null } },
    select: { baseMoveKey: true },
  })
  const existingMoveFlavorKeys = new Set(existingMoveFlavor.map(m => m.baseMoveKey as string))
  const wantMoves = fresh || existingMoveFlavorKeys.size < BASIC_MOVES.length
  let movesFlavored = 0
  if (wantMoves) {
    const moveFlavor = await generateMoveFlavor(
      campaign.title,
      campaign.description || '',
      campaign.universe || 'Original',
      (statLabelsSet ? generated.statLabels : (campaign.statLabels as any)) || undefined,
      lore.digest.slice(0, EXTRAS_DIGEST_CHARS)
    )
    if (moveFlavor && moveFlavor.length > 0) {
      const rollTypeByKey = new Map(BASIC_MOVES.map(m => [m.key, m.rollType]))
      const toCreate = fresh ? moveFlavor : moveFlavor.filter(m => !existingMoveFlavorKeys.has(m.baseMoveKey))
      if (toCreate.length > 0) {
        if (fresh && existingMoveFlavorKeys.size > 0) {
          await prisma.move.deleteMany({ where: { campaignId, baseMoveKey: { not: null } } })
        }
        await prisma.move.createMany({
          data: toCreate.map(m => ({
            campaignId,
            baseMoveKey: m.baseMoveKey,
            name: m.name,
            trigger: m.trigger,
            description: m.description,
            rollType: rollTypeByKey.get(m.baseMoveKey) || null,
            outcomes: m.outcomes,
            category: 'basic',
          })),
        })
        movesFlavored = toCreate.length
      }
    }
  }

  // --- Extras: archetypes + corruption theme + NPCs/locations -----------------
  // A live campaign with zero archetypes means a previous generation
  // attempt (fresh-mode, at creation or an earlier reseed) failed or was
  // interrupted partway through and never recovered — regenerate them here
  // too, so the admin "Reseed from lore" button is a real fix for that,
  // not just a fresh-mode-only escape hatch.
  const existingArchetypeCount = await prisma.campaignArchetype.count({ where: { campaignId } })
  const wantArchetypes = fresh || existingArchetypeCount === 0
  const wantTheme = fresh || !campaign.corruptionTheme

  let archetypesReplaced = 0
  let corruptionThemeSet = false
  let npcsAdded: string[] = []
  let locationsAdded: string[] = []
  // What the campaign's theme ends up being after this pass (used for the
  // shadow-branch invariant below). Starts as the current value.
  // #404: the shared predicate — a partially-filled theme is not a theme.
  let finalHasTheme = hasCorruptionTheme(campaign.corruptionTheme)

  {
    // Unlike archetypes/theme, NPCs/locations are always worth attempting
    // on a reseed (purely additive, same reasoning as fronts) — so this
    // call runs every time, not just when wantArchetypes/wantTheme need
    // refreshing.
    const allFactions = [
      ...existingFactions
        .filter(f => f.isActive && !plan.toRetire.includes(f.name))
        .map(f => ({ name: f.name, description: f.description || '' })),
      ...newFactions.map(f => ({ name: f.name, description: f.description })),
    ]
    const allCaps = [
      ...existingCaps.map(c => ({
        name: c.name, description: c.description || '', domain: c.domain, tier: c.tier, isSecret: c.isSecret,
      })),
      ...newCaps,
    ]
    const extras = await generateWorldExtras(
      campaign.title,
      campaign.description || '',
      campaign.universe || 'Original',
      allFactions,
      allCaps,
      (statLabelsSet ? generated.statLabels : (campaign.statLabels as any)) || undefined,
      lore.digest.slice(0, EXTRAS_DIGEST_CHARS)
    )

    if (extras) {
      const existingNpcs = await prisma.nPC.findMany({ where: { campaignId }, select: { name: true } })
      const newNpcNames = new Set(planFrontMerge(existingNpcs.map(n => n.name), extras.npcs.map(n => n.name)))
      const newNpcs = extras.npcs.filter(n => newNpcNames.has(n.name))
      if (newNpcs.length > 0) {
        await createNPCsForCampaign(campaignId, prisma, newNpcs)
        npcsAdded = newNpcs.map(n => n.name)
      }

      const existingLocations = await prisma.location.findMany({ where: { campaignId }, select: { name: true } })
      const newLocationNames = new Set(planFrontMerge(existingLocations.map(l => l.name), extras.locations.map(l => l.name)))
      const newLocations = extras.locations.filter(l => newLocationNames.has(l.name))
      if (newLocations.length > 0) {
        await createLocationsForCampaign(campaignId, prisma, newLocations)
        locationsAdded = newLocations.map(l => l.name)
      }

      if (wantTheme) {
        if (extras.corruptionTheme) {
          await prisma.campaign.update({
            where: { id: campaignId },
            data: { corruptionTheme: extras.corruptionTheme as object },
          })
          corruptionThemeSet = true
          finalHasTheme = true
        } else if (fresh && campaign.corruptionTheme) {
          // Canon says this universe has no power-at-a-cost concept — on a
          // fresh campaign that verdict replaces the provisional theme.
          await prisma.campaign.update({
            where: { id: campaignId },
            data: { corruptionTheme: Prisma.JsonNull },
          })
          finalHasTheme = false
        }
      }
      if (wantArchetypes && extras.archetypes.length > 0) {
        // Atomic: delete-then-recreate as two separate calls left a real
        // gap — a timeout or crash between them (this runs alongside two
        // sequential AI calls and a run of other DB writes, well within
        // reach of the request-handling reseed route's time budget) wiped
        // every archetype and never replaced them, silently and
        // permanently, with no error visible to the GM.
        const [, created] = await prisma.$transaction([
          prisma.campaignArchetype.deleteMany({ where: { campaignId } }),
          prisma.campaignArchetype.createMany({
            data: extras.archetypes.map(a => ({
              campaignId,
              name: a.name,
              description: a.description,
              originFamiliarity: a.originFamiliarity,
              suggestedStats: (a.suggestedStats as object | null) || undefined,
              startingGear: (a.startingGear as object | null) || undefined,
              startingTie: (a.startingTie as object | null) || undefined,
              backstoryPrompts: a.backstoryPrompts,
              glimpseCapabilityKeys: a.glimpseCapabilityKeys,
            })),
          }),
        ])
        archetypesReplaced = created.count
      }
    }
  }

  // --- World rules: Phase 4 semantic-invariant verdicts -----------------------
  // Same wantX gate as the corruption theme above (fresh, or this campaign
  // has never had a verdict) — never overwrites an admin/earlier-reseed
  // verdict in live mode. Its own AI call rather than folded into extras:
  // that call is already near its own token budget, and losing this to a
  // truncated response there would silently cost archetypes/theme too, not
  // just this.
  let worldRulesSet = false
  if (fresh || !campaign.worldRules) {
    const generatedRules = await generateWorldRules(
      campaign.title,
      campaign.description || '',
      campaign.universe || 'Original',
      lore.digest.slice(0, EXTRAS_DIGEST_CHARS)
    )
    if (generatedRules && generatedRules.length > 0) {
      const worldMeta = await prisma.worldMeta.findUnique({
        where: { campaignId },
        select: { currentTurnNumber: true },
      })
      await prisma.campaign.update({
        where: { id: campaignId },
        data: {
          worldRules: generatedRulesToWorldRules(generatedRules, worldMeta?.currentTurnNumber ?? 1) as object,
        },
      })
      worldRulesSet = true
    }
  }

  // --- World graph: #108 one-time adjacency backfill --------------------------
  // Row-count gate, not a single-column check, since LocationAdjacency is a
  // table of rows, not one JSON field — same shape as archetypes'
  // existingArchetypeCount gate above: a live campaign with zero rows is
  // treated as "never backfilled" (a recovery path), never overwriting a
  // prior/GM-adjusted graph otherwise.
  let worldGraphEdgesSet = 0
  const existingAdjacencyCount = await prisma.locationAdjacency.count({ where: { campaignId } })
  if (fresh || existingAdjacencyCount === 0) {
    const currentLocations = await prisma.location.findMany({
      where: { campaignId },
      select: { id: true, name: true, description: true },
    })
    if (currentLocations.length >= 2) {
      const generatedEdges = await generateWorldGraph(
        campaign.title,
        campaign.description || '',
        campaign.universe || 'Original',
        currentLocations.map((l) => ({ name: l.name, description: l.description })),
        lore.digest.slice(0, EXTRAS_DIGEST_CHARS)
      )
      if (generatedEdges && generatedEdges.length > 0) {
        const idByName = new Map(currentLocations.map((l) => [l.name, l.id]))
        const rows = generatedEdges
          .map((edge) => {
            const idA = idByName.get(edge.locationAName)
            const idB = idByName.get(edge.locationBName)
            if (!idA || !idB || idA === idB) return null
            // Canonicalize: locationAId always the lexicographically
            // smaller id, matching the schema's documented @@unique
            // convention (LocationAdjacency's own comment).
            const [locationAId, locationBId] = idA < idB ? [idA, idB] : [idB, idA]
            return { campaignId, locationAId, locationBId, distance: edge.distance }
          })
          .filter((row): row is { campaignId: string; locationAId: string; locationBId: string; distance: number } => row !== null)

        if (rows.length > 0) {
          const created = await prisma.locationAdjacency.createMany({ data: rows, skipDuplicates: true })
          worldGraphEdgesSet = created.count
        }
      }
    }
  }

  // --- Shadow branches: keep the corruption invariant --------------------------
  // Themed campaign: secret scaffold nodes are the forbidden arts
  // (idempotent re-mark). Fresh campaign whose theme just went away: clear
  // the flag so nothing stays gated on a track that no longer exists.
  if (finalHasTheme) {
    await prisma.campaignCapability.updateMany({
      where: { campaignId, isSecret: true },
      data: { isShadow: true },
    })
  } else if (fresh) {
    await prisma.campaignCapability.updateMany({
      where: { campaignId, isShadow: true },
      data: { isShadow: false },
    })
  }

  const summary: ReseedSummary = {
    fresh,
    loreEntriesSampled: lore.sampledEntries,
    loreEntriesTotal: lore.totalEntries,
    factionsAdded: newFactions.map(f => f.name),
    factionsRetired: plan.toRetire,
    factionsAlreadyPresent: generated.factions.length - newFactions.length,
    capabilitiesAdded: newCaps.map(c => c.name),
    frontsAdded: newFronts.map(f => f.name),
    npcsAdded,
    locationsAdded,
    statLabelsSet,
    corruptionThemeSet,
    archetypesReplaced,
    archetypesSkipped: !wantArchetypes,
    movesFlavored,
    worldRulesSet,
    worldGraphEdgesSet,
  }

  console.log(
    `🌍 Reseeded world from lore for ${campaignId} (${fresh ? 'fresh — replaced' : 'live — additive'}):` +
    ` +${summary.factionsAdded.length} factions (${summary.factionsRetired.length} retired),` +
    ` +${summary.capabilitiesAdded.length} capabilities, +${summary.frontsAdded.length} fronts,` +
    ` +${summary.npcsAdded.length} NPCs, +${summary.locationsAdded.length} locations,` +
    ` ${summary.movesFlavored} moves flavored` +
    ` (sampled ${lore.sampledEntries}/${lore.totalEntries} lore entries)`
  )

  return { ok: true, summary }
}
